version: '3.1'

services:

    mongo:
        image: mongo
        restart: always
        networks:
            mongo-net:
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        networks:
            mongo-net:
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
    mongo-net:
        ipam:
            driver: default
            config:
                - subnet: "23.1.1.0/24"
